Hi All, 

<p>The {% if client.name != client.subName %} {{client.name}} {{client.subName}} {% endif %}
{% if client.name == client.subName %} {{client.name}} {% endif %} visit has been rescheduled to new visit date {{startDate|date('d M Y')}} - {{endDate|date('d M Y')}}</p>
<br/>
<p>
Thanks.<br>
CSC India Visit Management Team<br>
<a href="https://c3.csc.com/groups/global-site-visit-management">Connect with us at on C3</a>
</p>